# SPDX-FileCopyrightText: 2021 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'dotnet-sdk'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      # These are bundeled (transitive) by MSTest.Sdk
      - dependency-name: Microsoft.NET.Test.Sdk
      - dependency-name: Microsoft.Testing.Extensions.CodeCoverage
      - dependency-name: Microsoft.Testing.Extensions.TrxReport
    groups:
      fluentui:
        patterns:
          - 'Microsoft.FluentUI.AspNetCore.Components*'
