<?xml version="1.0" encoding="utf-8"?>
<!--
SPDX-FileCopyrightText: 2026 Frans van Dorsselaer

SPDX-License-Identifier: MIT
-->
<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>$(MainTargetFramework)</TargetFramework>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Debounce\Debounce.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

</Project>
