# SPDX-FileCopyrightText: 2022 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json

# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

# APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
DISABLE_LINTERS:
  - CSHARP_DOTNET_FORMAT # Not compatible with .NET 9 (yet)
  - CSHARP_CSHARPIER # Not compatible with .NET 9 (yet)
  - CSHARP_ROSLYNATOR # Not compatible with .NET 9 (yet)
  - JSON_V8R # Too many missing/obsolete schemas
  - REPOSITORY_TRIVY # Unstable, leading to a lot of build failures
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
XML_XMLLINT_FILE_EXTENSIONS:
  - .xml
  - .xslt
  - .csproj
  - .props
  - .pubxml
  - .targets
  - .wixproj
  - .wxs
# Exclude verbatim copies of external sources that are not under our control.
# Also exclude auto-generated files.
FILTER_REGEX_EXCLUDE: COPYING\.md|LICENSE\.txt|LICENSES/|global.json|dotnet-tools.json
# Exclude additional binary files not already excluded by default.
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: (\.snk$)
