# SPDX-FileCopyrightText: 2026 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: NuGet

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      # checkov:skip=CKV_GHA_7: Required input for publishing an existing release to NuGet.
      tag_name:
        description: 'The existing release tag to publish (e.g., v1.2.0)'
        required: true
        type: string

permissions: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          cache: false

      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: |-
            ${{ case(
              github.event_name == 'release', github.event.release.tag_name,
              github.event_name == 'workflow_dispatch', github.event.inputs.tag_name,
              'unknown'
            ) }}
        run: |
          gh release download "${RELEASE_TAG}" --dir release-artifacts

      - name: NuGet Login (Trusted Publishing)
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: dorssel

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
        run: |
          PACKAGES=(./release-artifacts/*.nupkg)
          dotnet nuget push \
            "${PACKAGES[@]}" \
            --api-key "${NUGET_API_KEY}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate \
            --force-english-output
