# SPDX-FileCopyrightText: 2025 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Update Common Files

on:
  workflow_dispatch:
  schedule:
    - cron: '24 4 * * *'

permissions: {}

jobs:
  check:
    name: Check (common files)
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check for new .editorconfig
        run: |
          curl --fail --remote-name https://raw.githubusercontent.com/dorssel/workflows/refs/heads/main/.editorconfig

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: 'Update common files'
          title: 'Update common files'
          branch: update-common-files
          body: |
            This is an automated pull request, updating common files after a detected change
            in https://github.com/dorssel/workflows.
          sign-commits: true
